/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_inference_regression_NewRegressionJNIWrapper */

#ifndef _Included_dr_inference_regression_NewRegressionJNIWrapper
#define _Included_dr_inference_regression_NewRegressionJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef dr_inference_regression_NewRegressionJNIWrapper_NO_PRIOR
#define dr_inference_regression_NewRegressionJNIWrapper_NO_PRIOR 0L
#undef dr_inference_regression_NewRegressionJNIWrapper_LAPLACE_PRIOR
#define dr_inference_regression_NewRegressionJNIWrapper_LAPLACE_PRIOR 1L
#undef dr_inference_regression_NewRegressionJNIWrapper_NORMAL_PRIOR
#define dr_inference_regression_NewRegressionJNIWrapper_NORMAL_PRIOR 2L
/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    loadData
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_loadData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getLogLikelihood
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getLogLikelihood
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getLogLikelihoodGradient
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getLogLikelihoodGradient
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getLogPrior
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getLogPrior
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getBeta
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getBeta__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getBeta
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getBeta__I_3D
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getBetaSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getBetaSize
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_hasOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getHessian
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getHessian
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    setBeta
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_setBeta__IID
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    setBeta
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_setBeta__I_3D
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getHyperprior
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getHyperprior
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    setHyperprior
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_setHyperprior
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    findMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_findMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getUpdateCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getUpdateCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    getLikelihoodCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_getLikelihoodCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    setPriorType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_setPriorType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dr_inference_regression_NewRegressionJNIWrapper
 * Method:    makeDirty
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dr_inference_regression_NewRegressionJNIWrapper_makeDirty
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
