#!/bin/bash

export COPYFILE_DISABLE=true
cd ..

tar -zcvf BSCCS-packaged.tgz \
	--exclude="*.tgz" \
	--exclude=build/codebase \
	--exclude=data  \
	--exclude=bug \
	--exclude=presentations \
	--exclude=.svn \
	--exclude=make-tar \
	--exclude=.settings \
	--exclude=".*" \
	--exclude="*.o" \
	--exclude="*.out" \
	--exclude="*.log" \
	--exclude="build/ccd" \
	--exclude="build/CMake*" \
	--exclude="build/cmake*" \
	BSCCS
