# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('CCD_rcpp_hello_world', PACKAGE = 'CCD')
}

.ccdSetPrior <- function(inRcppCcdInterface, priorTypeName, variance, excludeNumeric) {
    invisible(.Call('CCD_ccdSetPrior', PACKAGE = 'CCD', inRcppCcdInterface, priorTypeName, variance, excludeNumeric))
}

.ccdPredictModel <- function(inRcppCcdInterface) {
    .Call('CCD_ccdPredictModel', PACKAGE = 'CCD', inRcppCcdInterface)
}

.ccdSetControl <- function(inRcppCcdInterface, maxIterations, tolerance, convergenceType, useAutoSearch, fold, foldToCompute, lowerLimit, upperLimit, gridSteps, noiseLevel) {
    invisible(.Call('CCD_ccdSetControl', PACKAGE = 'CCD', inRcppCcdInterface, maxIterations, tolerance, convergenceType, useAutoSearch, fold, foldToCompute, lowerLimit, upperLimit, gridSteps, noiseLevel))
}

.ccdRunCrossValidation <- function(inRcppCcdInterface) {
    .Call('CCD_ccdRunCrossValidationl', PACKAGE = 'CCD', inRcppCcdInterface)
}

.ccdFitModel <- function(inRcppCcdInterface) {
    .Call('CCD_ccdFitModel', PACKAGE = 'CCD', inRcppCcdInterface)
}

.ccdLogModel <- function(inRcppCcdInterface) {
    .Call('CCD_ccdLogModel', PACKAGE = 'CCD', inRcppCcdInterface)
}

.ccdInitializeModel <- function(inModelData, modelType, computeMLE = FALSE) {
    .Call('CCD_ccdInitializeModel', PACKAGE = 'CCD', inModelData, modelType, computeMLE)
}

.isRcppPtrNull <- function(x) {
    .Call('CCD_isRcppPtrNull', PACKAGE = 'CCD', x)
}

getNumberOfStrata <- function(x) {
    .Call('CCD_ccdGetNumberOfStrata', PACKAGE = 'CCD', x)
}

getNumberOfCovariates <- function(x) {
    .Call('CCD_ccdGetNumberOfColumns', PACKAGE = 'CCD', x)
}

getNumberOfRows <- function(x) {
    .Call('CCD_ccdGetNumberOfRows', PACKAGE = 'CCD', x)
}

.ccdReadSqlData <- function(oStratumId, oRowId, oY, oTime, cRowId, cCovariateId, cCovariateValue, modelTypeName) {
    .Call('CCD_ccdReadSqlData', PACKAGE = 'CCD', oStratumId, oRowId, oY, oTime, cRowId, cCovariateId, cCovariateValue, modelTypeName)
}

.ccdReadData <- function(fileName, modelTypeName) {
    .Call('CCD_ccdReadFileData', PACKAGE = 'CCD', fileName, modelTypeName)
}

.ccdModelData <- function(pid, y, z, offs, dx, sx, ix) {
    .Call('CCD_ccdModelData', PACKAGE = 'CCD', pid, y, z, offs, dx, sx, ix)
}

