# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cyclopsGetModelTypeNames <- function() {
    .Call('Cyclops2_cyclopsGetModelTypeNames', PACKAGE = 'Cyclops2')
}

.cyclopsGetRemoveInterceptNames <- function() {
    .Call('Cyclops2_cyclopsGetRemoveInterceptNames', PACKAGE = 'Cyclops2')
}

.cyclopsGetIsSurvivalNames <- function() {
    .Call('Cyclops2_cyclopsGetIsSurvivalNames', PACKAGE = 'Cyclops2')
}

.cyclopsGetUseOffsetNames <- function() {
    .Call('Cyclops2_cyclopsGetUseOffsetNames', PACKAGE = 'Cyclops2')
}

.cyclopsSetBeta <- function(inRcppCcdInterface, beta) {
    invisible(.Call('Cyclops2_cyclopsSetBeta', PACKAGE = 'Cyclops2', inRcppCcdInterface, beta))
}

.cyclopsSetFixedBeta <- function(inRcppCcdInterface, beta, fixed) {
    invisible(.Call('Cyclops2_cyclopsSetFixedBeta', PACKAGE = 'Cyclops2', inRcppCcdInterface, beta, fixed))
}

.cyclopsGetIsRegularized <- function(inRcppCcdInterface, index) {
    .Call('Cyclops2_cyclopsGetIsRegularized', PACKAGE = 'Cyclops2', inRcppCcdInterface, index)
}

.cyclopsSetWeights <- function(inRcppCcdInterface, weights) {
    invisible(.Call('Cyclops2_cyclopsSetWeights', PACKAGE = 'Cyclops2', inRcppCcdInterface, weights))
}

.cyclopsGetPredictiveLogLikelihood <- function(inRcppCcdInterface, weights) {
    .Call('Cyclops2_cyclopsGetPredictiveLogLikelihood', PACKAGE = 'Cyclops2', inRcppCcdInterface, weights)
}

.cyclopsGetLogLikelihood <- function(inRcppCcdInterface) {
    .Call('Cyclops2_cyclopsGetLogLikelihood', PACKAGE = 'Cyclops2', inRcppCcdInterface)
}

.cyclopsGetFisherInformation <- function(inRcppCcdInterface, sexpCovariates) {
    .Call('Cyclops2_cyclopsGetFisherInformation', PACKAGE = 'Cyclops2', inRcppCcdInterface, sexpCovariates)
}

.cyclopsSetPrior <- function(inRcppCcdInterface, priorTypeName, variance, excludeNumeric, sexpGraph) {
    invisible(.Call('Cyclops2_cyclopsSetPrior', PACKAGE = 'Cyclops2', inRcppCcdInterface, priorTypeName, variance, excludeNumeric, sexpGraph))
}

.cyclopsProfileModel <- function(inRcppCcdInterface, sexpCovariates, threshold, override, includePenalty) {
    .Call('Cyclops2_cyclopsProfileModel', PACKAGE = 'Cyclops2', inRcppCcdInterface, sexpCovariates, threshold, override, includePenalty)
}

.cyclopsPredictModel <- function(inRcppCcdInterface) {
    .Call('Cyclops2_cyclopsPredictModel', PACKAGE = 'Cyclops2', inRcppCcdInterface)
}

.cyclopsSetControl <- function(inRcppCcdInterface, maxIterations, tolerance, convergenceType, useAutoSearch, fold, foldToCompute, lowerLimit, upperLimit, gridSteps, noiseLevel, threads, seed, resetCoefficients, startingVariance, useKKTSwindle, swindleMultipler, selectorType) {
    invisible(.Call('Cyclops2_cyclopsSetControl', PACKAGE = 'Cyclops2', inRcppCcdInterface, maxIterations, tolerance, convergenceType, useAutoSearch, fold, foldToCompute, lowerLimit, upperLimit, gridSteps, noiseLevel, threads, seed, resetCoefficients, startingVariance, useKKTSwindle, swindleMultipler, selectorType))
}

.cyclopsRunCrossValidation <- function(inRcppCcdInterface) {
    .Call('Cyclops2_cyclopsRunCrossValidationl', PACKAGE = 'Cyclops2', inRcppCcdInterface)
}

.cyclopsFitModel <- function(inRcppCcdInterface) {
    .Call('Cyclops2_cyclopsFitModel', PACKAGE = 'Cyclops2', inRcppCcdInterface)
}

.cyclopsLogModel <- function(inRcppCcdInterface) {
    .Call('Cyclops2_cyclopsLogModel', PACKAGE = 'Cyclops2', inRcppCcdInterface)
}

.cyclopsInitializeModel <- function(inModelData, modelType, computeMLE = FALSE) {
    .Call('Cyclops2_cyclopsInitializeModel', PACKAGE = 'Cyclops2', inModelData, modelType, computeMLE)
}

.isSorted <- function(dataFrame, indexes, ascending) {
    .Call('Cyclops2_isSorted', PACKAGE = 'Cyclops2', dataFrame, indexes, ascending)
}

#' @title Print row identifiers
#' 
#' @description
#' \code{printCcdRowIds} return the row identifiers in a Cyclops data object
#' 
#' @param object    A Cyclops data object
#' 
#' @keywords internal
printCyclopsRowIds <- function(object) {
    invisible(.Call('Cyclops2_cyclopsPrintRowIds', PACKAGE = 'Cyclops2', object))
}

.isRcppPtrNull <- function(x) {
    .Call('Cyclops2_isRcppPtrNull', PACKAGE = 'Cyclops2', x)
}

#' @title Get number of strata
#' 
#' @description
#' \code{getNumberOfStrata} return the number of unique strata in a Cyclops data object
#' 
#' @param object    A Cyclops data object
#' 
#' @export
getNumberOfStrata <- function(object) {
    .Call('Cyclops2_cyclopsGetNumberOfStrata', PACKAGE = 'Cyclops2', object)
}

#' @title Get covariate identifiers
#' 
#' @description
#' \code{getCovariateIds} returns a vector of integer covariate identifiers in a Cyclops data object
#' 
#' @param object    A Cyclops data object
#' 
#' @export
getCovariateIds <- function(object) {
    .Call('Cyclops2_cyclopsGetCovariateIds', PACKAGE = 'Cyclops2', object)
}

#' @title Get covariate types
#' 
#' @description
#' \code{getCovariateTypes} returns a vector covariate types in a Cyclops data object
#' 
#' @param object    A Cyclops data object
#' @param covariateLabel Integer vector: covariate identifiers to return
#' 
#' @export
getCovariateTypes <- function(object, covariateLabel) {
    .Call('Cyclops2_cyclopsGetCovariateType', PACKAGE = 'Cyclops2', object, covariateLabel)
}

#' @title Get total number of covariates
#' 
#' @description
#' \code{getNumberOfCovariates} returns the total number of covariates in a Cyclops data object
#' 
#' @param object    A Cyclops data object
#'
#' @export
getNumberOfCovariates <- function(object) {
    .Call('Cyclops2_cyclopsGetNumberOfColumns', PACKAGE = 'Cyclops2', object)
}

#' @title Get total number of rows
#' 
#' @description
#' \code{getNumberOfRows} returns the total number of outcome rows in a Cyclops data object
#' 
#' @param object    A Cyclops data object
#'
#' @export
getNumberOfRows <- function(object) {
    .Call('Cyclops2_cyclopsGetNumberOfRows', PACKAGE = 'Cyclops2', object)
}

#' @title Get total number of outcome types
#' 
#' @description
#' \code{getNumberOfTypes} returns the total number of outcome types in a Cyclops data object
#' 
#' @param object    A Cyclops data object
#'
#' @keywords internal
getNumberOfTypes <- function(object) {
    .Call('Cyclops2_cyclopsGetNumberOfTypes', PACKAGE = 'Cyclops2', object)
}

.cyclopsSumByGroup <- function(x, covariateLabel, groupByLabel, power) {
    .Call('Cyclops2_cyclopsSumByGroup', PACKAGE = 'Cyclops2', x, covariateLabel, groupByLabel, power)
}

.cyclopsSumByStratum <- function(x, covariateLabel, power) {
    .Call('Cyclops2_cyclopsSumByStratum', PACKAGE = 'Cyclops2', x, covariateLabel, power)
}

.cyclopsSum <- function(x, covariateLabel, power) {
    .Call('Cyclops2_cyclopsSum', PACKAGE = 'Cyclops2', x, covariateLabel, power)
}

.cyclopsNewSqlData <- function(modelTypeName, noiseLevel) {
    .Call('Cyclops2_cyclopsNewSqlData', PACKAGE = 'Cyclops2', modelTypeName, noiseLevel)
}

.cyclopsSetHasIntercept <- function(x, hasIntercept) {
    invisible(.Call('Cyclops2_cyclopsSetHasIntercept', PACKAGE = 'Cyclops2', x, hasIntercept))
}

.cyclopsGetHasIntercept <- function(x) {
    .Call('Cyclops2_cyclopsGetHasIntercept', PACKAGE = 'Cyclops2', x)
}

.cyclopsGetHasOffset <- function(x) {
    .Call('Cyclops2_cyclopsGetHasOffset', PACKAGE = 'Cyclops2', x)
}

.cyclopsFinalizeData <- function(x, addIntercept, sexpOffsetCovariate, offsetAlreadyOnLogScale, sortCovariates, sexpCovariatesDense, magicFlag = FALSE) {
    invisible(.Call('Cyclops2_cyclopsFinalizeData', PACKAGE = 'Cyclops2', x, addIntercept, sexpOffsetCovariate, offsetAlreadyOnLogScale, sortCovariates, sexpCovariatesDense, magicFlag))
}

.appendSqlCyclopsData <- function(x, oStratumId, oRowId, oY, oTime, cRowId, cCovariateId, cCovariateValue) {
    .Call('Cyclops2_cyclopsAppendSqlData', PACKAGE = 'Cyclops2', x, oStratumId, oRowId, oY, oTime, cRowId, cCovariateId, cCovariateValue)
}

.cyclopsGetInterceptLabel <- function(x) {
    .Call('Cyclops2_cyclopsGetInterceptLabel', PACKAGE = 'Cyclops2', x)
}

.cyclopsReadData <- function(fileName, modelTypeName) {
    .Call('Cyclops2_cyclopsReadFileData', PACKAGE = 'Cyclops2', fileName, modelTypeName)
}

.cyclopsModelData <- function(pid, y, z, offs, dx, sx, ix, modelTypeName, useTimeAsOffset = FALSE, numTypes = 1L) {
    .Call('Cyclops2_cyclopsModelData', PACKAGE = 'Cyclops2', pid, y, z, offs, dx, sx, ix, modelTypeName, useTimeAsOffset, numTypes)
}

